/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate and start a session. */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the refresh token and issue a new token pair. */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the session for the presented refresh token. */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user, role, and effective permission keys. */
    get: operations['MeController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Staff and Admin accounts with their granted keys. */
    get: operations['UsersController_list'];
    put?: never;
    /** Create a Staff or Admin account with an Admin-set password. */
    post: operations['UsersController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lockout recovery: set a new password, revoke sessions, audit (D-047). */
    post: operations['UsersController_resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the grants held by one user. */
    get: operations['UsersController_listPermissions'];
    put?: never;
    /** Grant a permission by key. */
    post: operations['UsersController_grant'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/permissions/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a permission by key. */
    delete: operations['UsersController_revoke'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the permission catalogue. */
    get: operations['PermissionsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/worlds': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** World tree with Trick counts and computed completion rollup. */
    get: operations['WorldsController_list'];
    put?: never;
    /** Create a World. */
    post: operations['WorldsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/worlds/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Reorder Worlds by an explicit ordered id array. */
    put: operations['WorldsController_reorder'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/worlds/{worldId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a World name/description. */
    patch: operations['WorldsController_update'];
    trace?: never;
  };
  '/api/tricks/{trickId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trick detail with variants and computed completeness. */
    get: operations['TricksController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Trick fields; each touched field is permission-checked. */
    patch: operations['TricksController_update'];
    trace?: never;
  };
  '/api/tricks/{trickId}/variants/{ageTier}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Upsert an age-tier content variant. */
    put: operations['TricksController_upsertVariant'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Preview the selected age-tier content. */
    get: operations['TricksController_preview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Snapshot history, newest first (read-only). */
    get: operations['TricksController_versions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/worlds/{worldId}/tricks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a Trick at the next position and snapshot it. */
    post: operations['WorldTricksController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/worlds/{worldId}/tricks/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Reorder Tricks within a World by an explicit ordered id array. */
    put: operations['WorldTricksController_reorder'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/worlds/{worldId}/curriculums': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Curricula for a World with sequence counts and computed completion. */
    get: operations['WorldCurriculumsController_list'];
    put?: never;
    /** Create a Curriculum for a World. */
    post: operations['WorldCurriculumsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/curriculums/{curriculumId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Curriculum detail with ordered Sequences and their Trick roles. */
    get: operations['CurriculumsController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Curriculum name/description/version/status. */
    patch: operations['CurriculumsController_update'];
    trace?: never;
  };
  '/api/curriculums/{curriculumId}/sequences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a Sequence at the next sequenceNumber. */
    post: operations['CurriculumsController_createSequence'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/curriculums/{curriculumId}/sequences/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Reorder a Curriculum’s Sequences by an explicit ordered id array. */
    put: operations['CurriculumsController_reorderSequences'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sequences/{sequenceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Sequence name/objective/difficulty description/status. */
    patch: operations['SequencesController_update'];
    trace?: never;
  };
  '/api/sequences/{sequenceId}/tricks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set/replace the ordered Trick role assignment list. */
    put: operations['SequencesController_setTricks'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/fact-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Typed Fact registry metadata (factType names and field hints). */
    get: operations['FactTypesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/families': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Families with type and Fact counts. */
    get: operations['FamiliesController_list'];
    put?: never;
    /** Create a Nitty Gritty Family. */
    post: operations['FamiliesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/families/{familyId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Family detail with its ordered Facts. */
    get: operations['FamiliesController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update name/type/recurrence/threshold/World bindings. */
    patch: operations['FamiliesController_update'];
    trace?: never;
  };
  '/api/families/{familyId}/facts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a Fact at the next order with its first snapshot. */
    post: operations['FamiliesController_createFact'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/families/{familyId}/facts/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Reorder a Family’s Facts by an explicit ordered id array. */
    put: operations['FamiliesController_reorderFacts'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/facts/{factId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fact detail with typed data and validation state. */
    get: operations['FactsController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a Fact (writes an attributed snapshot). */
    patch: operations['FactsController_update'];
    trace?: never;
  };
  '/api/facts/{factId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fact snapshot history, newest first. */
    get: operations['FactsController_versions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sequences/{sequenceId}/insertions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ordered Nitty Gritty insertions for a Sequence. */
    get: operations['InsertionsController_list'];
    /** Set/replace the ordered insertion list for a Sequence. */
    put: operations['InsertionsController_replace'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/vetting': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Trick vetting status; VERIFIED requires all three fields (D-041). */
    put: operations['TrustTricksController_setVetting'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Trick review status (human approval; D-042). */
    put: operations['TrustTricksController_setReview'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a Trick; validates the atomic publication gate (D-043). */
    post: operations['TrustTricksController_publish'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/unpublish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Clear a Trick’s publishedAt. */
    post: operations['TrustTricksController_unpublish'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Threaded comments for a Trick, oldest first. */
    get: operations['TrustTricksController_listComments'];
    put?: never;
    /** Add a comment or threaded reply (any Staff/Admin). */
    post: operations['TrustTricksController_createComment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tricks/{trickId}/versions/{versionId}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a prior Trick version as a new audited mutation (D-044). */
    post: operations['TrustTricksController_restoreVersion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/trick-variants/{variantId}/review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set a content variant’s review status (human approval; D-042). */
    put: operations['TrustVariantsController_setReview'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/comments/{commentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Resolve/reopen or reassign a comment (comment.coordinate; D-045). */
    patch: operations['TrustCommentsController_update'];
    trace?: never;
  };
  '/api/facts/{factId}/vetting': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set a Fact vetting status (D-041). */
    put: operations['TrustFactsController_setVetting'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/facts/{factId}/review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set a Fact review status (human approval; D-042). */
    put: operations['TrustFactsController_setReview'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/facts/{factId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish a Fact; validates the atomic publication gate (D-043). */
    post: operations['TrustFactsController_publish'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/facts/{factId}/versions/{versionId}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a prior Fact version as a new audited mutation (D-044). */
    post: operations['TrustFactsController_restoreVersion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ops/completion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Per-World verified/publication-ready counts and percentages. */
    get: operations['OpsController_completion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ops/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Newest-first recent content mutations, bounded and paginated. */
    get: operations['OpsController_activity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness plus a database state read (always 200). */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness: 200 when the database is reachable, 503 otherwise. */
    get: operations['HealthController_ready'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /**
       * Format: email
       * @example admin@mathsalot.example
       */
      email: string;
      password: string;
    };
    SessionUserDto: {
      id: string;
      /** Format: email */
      email: string;
      displayName: string;
      /** @enum {string} */
      role: 'ADMIN' | 'STAFF' | 'LEARNER';
      /** @description True for Admin accounts, which bypass permission grants. */
      isAdmin: boolean;
      /** @description Effective permission keys. */
      permissions: string[];
    };
    AuthSessionDto: {
      /** @description Short-lived HS256 access token. */
      accessToken: string;
      /** @description Opaque refresh token. Store server-side only. */
      refreshToken: string;
      /**
       * @example Bearer
       * @enum {string}
       */
      tokenType: 'Bearer';
      /**
       * @description Access token lifetime in seconds.
       * @example 900
       */
      expiresIn: number;
      user: components['schemas']['SessionUserDto'];
    };
    RefreshTokenDto: {
      /** @description Opaque refresh token issued by login or refresh. */
      refreshToken: string;
    };
    LogoutResponseDto: {
      /**
       * @example true
       * @enum {boolean}
       */
      success: true;
    };
    MeDto: {
      id: string;
      /** Format: email */
      email: string;
      displayName: string;
      /** @enum {string} */
      role: 'ADMIN' | 'STAFF' | 'LEARNER';
      isAdmin: boolean;
      permissions: string[];
    };
    UserSummaryDto: {
      id: string;
      /** Format: email */
      email: string;
      displayName: string;
      /** @enum {string} */
      role: 'ADMIN' | 'STAFF' | 'LEARNER';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastLoginAt: string | null;
      /** @description Granted permission keys. */
      permissions: string[];
    };
    CreateUserDto: {
      /** Format: email */
      email: string;
      displayName: string;
      /** @enum {string} */
      role: 'ADMIN' | 'STAFF';
      password: string;
    };
    ResetUserPasswordDto: {
      password: string;
    };
    ResetPasswordResponseDto: {
      /**
       * @example true
       * @enum {boolean}
       */
      success: true;
      /** @description Number of the target user’s sessions revoked. */
      revokedSessions: number;
    };
    UserPermissionDto: {
      /** @example trick.content.write */
      key: string;
      /** @example Write Trick wording, scenarios, and worked examples per age tier */
      label: string;
      /** Format: date-time */
      grantedAt: string;
    };
    GrantPermissionDto: {
      /** @example trick.content.write */
      key: string;
    };
    RevokePermissionResponseDto: {
      /**
       * @example true
       * @enum {boolean}
       */
      success: true;
      /** @description True when a grant existed and was removed. */
      removed: boolean;
    };
    PermissionDto: {
      /** @example trick.content.write */
      key: string;
      /** @example Write Trick wording, scenarios, and worked examples per age tier */
      label: string;
    };
    WorldRollupDto: {
      trickCount: number;
      completeTrickCount: number;
      readyTrickCount: number;
      completionPercent: number;
    };
    CompletenessDto: {
      variantCount: number;
      /** @example 3 */
      totalTiers: number;
      missingTiers: ('FORMATIVE' | 'MIDRANGE' | 'MATURE')[];
      isComplete: boolean;
      /** @description Complete, verified, approved, and all variants approved. */
      isReady: boolean;
    };
    TrickSummaryDto: {
      id: string;
      name: string;
      /** @enum {string} */
      kind: 'STANDARD' | 'CAPSTONE';
      position: number;
      completeness: components['schemas']['CompletenessDto'];
    };
    WorldSummaryDto: {
      id: string;
      name: string;
      description: string | null;
      order: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      rollup: components['schemas']['WorldRollupDto'];
      tricks: components['schemas']['TrickSummaryDto'][];
    };
    CreateWorldDto: {
      name: string;
      description?: string | null;
    };
    ReorderDto: {
      /** @description Every current member id, in the desired 1..n order. */
      orderedIds: string[];
    };
    ReorderResponseDto: {
      orderedIds: string[];
    };
    UpdateWorldDto: {
      name?: string;
      description?: string | null;
    };
    VariantDto: {
      id: string;
      /** @enum {string} */
      ageTier: 'FORMATIVE' | 'MIDRANGE' | 'MATURE';
      wording: string;
      scenario: string;
      readingLevel: string | null;
      /** @enum {string} */
      draftSource: 'HUMAN' | 'AI';
      /** @enum {string} */
      reviewStatus: 'NEEDS_REVIEW' | 'APPROVED';
      /** Format: date-time */
      updatedAt: string;
    };
    TrickDetailDto: {
      id: string;
      worldId: string;
      name: string;
      /** @enum {string} */
      kind: 'STANDARD' | 'CAPSTONE';
      position: number;
      methodDescription: string;
      workedExample: string | null;
      /** @enum {string} */
      vettingStatus: 'DRAFT' | 'UNDER_REVIEW' | 'VERIFIED' | 'NEEDS_REVISION';
      /** @description Required before VERIFIED (D-041). */
      vettingValidity: string | null;
      /** @description Required before VERIFIED (D-041). */
      vettingDomain: string | null;
      /** @description Required before VERIFIED (D-041). */
      vettingEdgeCases: string | null;
      /** @enum {string} */
      draftSource: 'HUMAN' | 'AI';
      /** @enum {string} */
      reviewStatus: 'NEEDS_REVIEW' | 'APPROVED';
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      variants: components['schemas']['VariantDto'][];
      completeness: components['schemas']['CompletenessDto'];
    };
    UpdateTrickDto: {
      name?: string;
      /** @enum {string} */
      kind?: 'STANDARD' | 'CAPSTONE';
      methodDescription?: string;
      workedExample?: string | null;
    };
    UpsertVariantDto: {
      wording: string;
      scenario: string;
      readingLevel?: string | null;
      /**
       * @description AI drafts default to NEEDS_REVIEW and stay blocked until approved (D-042).
       * @enum {string}
       */
      draftSource?: 'HUMAN' | 'AI';
    };
    PreviewDto: {
      trickId: string;
      /** @enum {string} */
      ageTier: 'FORMATIVE' | 'MIDRANGE' | 'MATURE';
      wording: string;
      scenario: string;
      readingLevel: string | null;
    };
    TrickVersionDto: {
      id: string;
      trickId: string;
      editedById: string;
      /** Format: date-time */
      editedAt: string;
      /** @description Full Trick snapshot captured at this revision. */
      snapshot: {
        [key: string]: unknown;
      };
    };
    CreateTrickDto: {
      name: string;
      /**
       * @default STANDARD
       * @enum {string}
       */
      kind: 'STANDARD' | 'CAPSTONE';
      methodDescription: string;
      workedExample?: string | null;
      /**
       * @description AI drafts default to NEEDS_REVIEW and stay blocked until approved (D-042).
       * @default HUMAN
       * @enum {string}
       */
      draftSource: 'HUMAN' | 'AI';
    };
    CurriculumCompletionDto: {
      sequenceCount: number;
      completeSequenceCount: number;
      assignmentCount: number;
      coveredTrickCount: number;
      introduceCount: number;
      retainCount: number;
      revisitCount: number;
      completionPercent: number;
    };
    CurriculumSummaryDto: {
      id: string;
      worldId: string;
      name: string;
      description: string | null;
      version: string;
      /** @enum {string} */
      status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      completion: components['schemas']['CurriculumCompletionDto'];
    };
    CreateCurriculumDto: {
      name: string;
      description?: string | null;
      /** @description Version label, e.g. "v1". */
      version: string;
      /**
       * @default DRAFT
       * @enum {string}
       */
      status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
    };
    SequenceCompletionDto: {
      assignmentCount: number;
      introduceCount: number;
      retainCount: number;
      revisitCount: number;
      isComplete: boolean;
    };
    SequenceTrickDto: {
      id: string;
      trickId: string;
      /** @enum {string} */
      role: 'INTRODUCE' | 'RETAIN' | 'REVISIT';
      position: number;
    };
    SequenceDetailDto: {
      id: string;
      curriculumId: string;
      sequenceNumber: number;
      name: string;
      objective: string;
      description: string | null;
      difficultyDescription: string | null;
      /** @enum {string} */
      status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
      completion: components['schemas']['SequenceCompletionDto'];
      tricks: components['schemas']['SequenceTrickDto'][];
    };
    CurriculumDetailDto: {
      id: string;
      worldId: string;
      name: string;
      description: string | null;
      version: string;
      /** @enum {string} */
      status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      completion: components['schemas']['CurriculumCompletionDto'];
      sequences: components['schemas']['SequenceDetailDto'][];
    };
    UpdateCurriculumDto: {
      name?: string;
      description?: string | null;
      version?: string;
      /** @enum {string} */
      status?: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
    };
    CreateSequenceDto: {
      name: string;
      objective: string;
      description?: string | null;
      difficultyDescription?: string | null;
      /**
       * @default DRAFT
       * @enum {string}
       */
      status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
    };
    UpdateSequenceDto: {
      name?: string;
      objective?: string;
      description?: string | null;
      difficultyDescription?: string | null;
      /** @enum {string} */
      status?: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';
    };
    SequenceTrickAssignmentDto: {
      trickId: string;
      /** @enum {string} */
      role: 'INTRODUCE' | 'RETAIN' | 'REVISIT';
      /** @description 1..n position; the full list must be gap-free. */
      position: number;
    };
    SetSequenceTricksDto: {
      tricks: components['schemas']['SequenceTrickAssignmentDto'][];
    };
    FactFieldDto: {
      name: string;
      /** @enum {string} */
      type: 'string' | 'number' | 'string[]';
      required: boolean;
      description: string;
    };
    FactTypeDto: {
      type: string;
      description: string;
      fields: components['schemas']['FactFieldDto'][];
    };
    FamilySummaryDto: {
      id: string;
      name: string;
      /** @enum {string} */
      type: 'WORLD_BOUND' | 'GLOBAL';
      boundWorldId: string | null;
      triggerWorldId: string | null;
      recurrenceInitialInterval: number;
      recurrenceGrowthFactor: number;
      instantRecallThresholdMs: number;
      /** @description Number of Facts in this Family. */
      factCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateFamilyDto: {
      name: string;
      /** @enum {string} */
      type: 'WORLD_BOUND' | 'GLOBAL';
      /** @description WORLD_BOUND only. */
      boundWorldId?: string | null;
      /** @description GLOBAL only. */
      triggerWorldId?: string | null;
      recurrenceInitialInterval: number;
      /** @description Must be greater than zero. */
      recurrenceGrowthFactor: number;
      instantRecallThresholdMs: number;
    };
    FactValidationDto: {
      /** @description Whether the stored structured data validates against its type. */
      valid: boolean;
      errors: string[];
    };
    FactDetailDto: {
      id: string;
      familyId: string;
      order: number;
      /** @enum {string} */
      factType: 'operation' | 'equivalence' | 'calendar';
      /** @description Structured data validated against `factType`. */
      data: {
        [key: string]: unknown;
      };
      factText: string;
      numberRangeMin: number | null;
      numberRangeMax: number | null;
      gatingRequired: boolean;
      /** @enum {string} */
      vettingStatus: 'DRAFT' | 'UNDER_REVIEW' | 'VERIFIED' | 'NEEDS_REVISION';
      /** @enum {string} */
      draftSource: 'HUMAN' | 'AI';
      /** @enum {string} */
      reviewStatus: 'NEEDS_REVIEW' | 'APPROVED';
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      validation: components['schemas']['FactValidationDto'];
    };
    FamilyDetailDto: {
      id: string;
      name: string;
      /** @enum {string} */
      type: 'WORLD_BOUND' | 'GLOBAL';
      boundWorldId: string | null;
      triggerWorldId: string | null;
      recurrenceInitialInterval: number;
      recurrenceGrowthFactor: number;
      instantRecallThresholdMs: number;
      /** @description Number of Facts in this Family. */
      factCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description Facts in deterministic 1..n order. */
      facts: components['schemas']['FactDetailDto'][];
    };
    UpdateFamilyDto: {
      name?: string;
      /** @enum {string} */
      type?: 'WORLD_BOUND' | 'GLOBAL';
      boundWorldId?: string | null;
      triggerWorldId?: string | null;
      recurrenceInitialInterval?: number;
      /** @description Must be greater than zero. */
      recurrenceGrowthFactor?: number;
      instantRecallThresholdMs?: number;
    };
    CreateFactDto: {
      /** @enum {string} */
      factType: 'operation' | 'equivalence' | 'calendar';
      /** @description Validated against the registered `factType` schema. */
      data: {
        [key: string]: unknown;
      };
      factText: string;
      /** @description WORLD_BOUND Facts only. */
      numberRangeMin?: number | null;
      /** @description WORLD_BOUND Facts only. */
      numberRangeMax?: number | null;
      /** @default false */
      gatingRequired: boolean;
      /**
       * @description AI drafts default to NEEDS_REVIEW and stay blocked until approved (D-042).
       * @default HUMAN
       * @enum {string}
       */
      draftSource: 'HUMAN' | 'AI';
    };
    ReorderFactsDto: {
      /** @description Every current Fact id, in the desired 1..n order. */
      orderedIds: string[];
    };
    OrderedIdsResponseDto: {
      orderedIds: string[];
    };
    UpdateFactDto: {
      /** @enum {string} */
      factType?: 'operation' | 'equivalence' | 'calendar';
      /** @description Validated against the effective `factType`. */
      data?: {
        [key: string]: unknown;
      };
      factText?: string;
      numberRangeMin?: number | null;
      numberRangeMax?: number | null;
      gatingRequired?: boolean;
    };
    FactVersionDto: {
      id: string;
      factId: string;
      editedById: string;
      /** Format: date-time */
      editedAt: string;
      /** @description Full Fact snapshot captured at this revision. */
      snapshot: {
        [key: string]: unknown;
      };
    };
    InsertionDto: {
      id: string;
      sequenceId: string;
      factId: string;
      /** @enum {string} */
      insertionType: 'gating' | 'alongside';
      position: number;
    };
    InsertionInputDto: {
      factId: string;
      /** @enum {string} */
      insertionType: 'gating' | 'alongside';
      /** @description 1..n position; the full list must be gap-free. */
      position: number;
    };
    SetInsertionsDto: {
      insertions: components['schemas']['InsertionInputDto'][];
    };
    SetTrickVettingDto: {
      /** @enum {string} */
      status: 'DRAFT' | 'UNDER_REVIEW' | 'VERIFIED' | 'NEEDS_REVISION';
      /** @description Required (non-empty) before status may be VERIFIED (D-041). */
      vettingValidity?: string | null;
      /** @description Required (non-empty) before status may be VERIFIED (D-041). */
      vettingDomain?: string | null;
      /** @description Required (non-empty) before status may be VERIFIED (D-041). */
      vettingEdgeCases?: string | null;
    };
    SetReviewDto: {
      /** @enum {string} */
      reviewStatus: 'NEEDS_REVIEW' | 'APPROVED';
    };
    CommentDto: {
      id: string;
      trickId: string;
      parentCommentId: string | null;
      authorId: string;
      body: string;
      /** @enum {string} */
      status: 'OPEN' | 'RESOLVED';
      assignedToId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description Direct replies, oldest first. */
      replies: components['schemas']['CommentDto'][];
    };
    CreateCommentDto: {
      body: string;
      /** @description Parent comment for a threaded reply; must belong to the same Trick. */
      parentCommentId?: string | null;
    };
    UpdateCommentDto: {
      /** @enum {string} */
      status?: 'OPEN' | 'RESOLVED';
      /** @description Staff/Admin user to assign; null clears the assignee. */
      assignedToId?: string | null;
    };
    SetFactVettingDto: {
      /** @enum {string} */
      status: 'DRAFT' | 'UNDER_REVIEW' | 'VERIFIED' | 'NEEDS_REVISION';
    };
    WorldCompletionDto: {
      worldId: string;
      worldName: string;
      /** @description World ordering, ascending. */
      order: number;
      totalTricks: number;
      /** @description Tricks with vetting status VERIFIED. */
      verifiedTricks: number;
      /** @description Tricks with publishedAt set (publication-ready). */
      publishedTricks: number;
      verifiedPercent: number;
      publishedPercent: number;
    };
    CompletionSummaryDto: {
      totalTricks: number;
      verifiedTricks: number;
      publishedTricks: number;
      verifiedPercent: number;
      publishedPercent: number;
    };
    CompletionReportDto: {
      worlds: components['schemas']['WorldCompletionDto'][];
      overall: components['schemas']['CompletionSummaryDto'];
    };
    ActivityActorDto: {
      id: string;
      displayName: string;
    };
    ActivityItemDto: {
      id: string;
      /** @example trick.vetting.updated */
      action: string;
      /** @example Trick */
      targetType: string | null;
      targetId: string | null;
      /** Format: date-time */
      occurredAt: string;
      actor: components['schemas']['ActivityActorDto'] | null;
    };
    ActivityPageDto: {
      items: components['schemas']['ActivityItemDto'][];
      /** @description Total content mutations available. */
      total: number;
      limit: number;
      offset: number;
      hasMore: boolean;
    };
    HealthResponseDto: {
      /**
       * @example ok
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /**
       * @example up
       * @enum {string}
       */
      database: 'up' | 'down';
      /**
       * Format: date-time
       * @example 2026-01-01T00:00:00.000Z
       */
      timestamp: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSessionDto'];
        };
      };
      /** @description Invalid email or password. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Too many login attempts. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSessionDto'];
        };
      };
      /** @description Invalid, expired, or reused refresh token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Too many refresh attempts. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogoutResponseDto'];
        };
      };
    };
  };
  MeController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeDto'];
        };
      };
    };
  };
  UsersController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSummaryDto'][];
        };
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSummaryDto'];
        };
      };
      /** @description Invalid role or payload. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetUserPasswordDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResetPasswordResponseDto'];
        };
      };
      /** @description Weak password or Learner target. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown user. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_listPermissions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserPermissionDto'][];
        };
      };
      /** @description Unknown user. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_grant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GrantPermissionDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserPermissionDto'][];
        };
      };
      /** @description Unknown key or Admin target. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown user. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RevokePermissionResponseDto'];
        };
      };
      /** @description Unknown key or Admin target. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown user. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PermissionsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermissionDto'][];
        };
      };
    };
  };
  WorldsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorldSummaryDto'][];
        };
      };
    };
  };
  WorldsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorldDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorldSummaryDto'];
        };
      };
    };
  };
  WorldsController_reorder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReorderResponseDto'];
        };
      };
    };
  };
  WorldsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        worldId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateWorldDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorldSummaryDto'];
        };
      };
      /** @description Unknown World. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TricksController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TricksController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTrickDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TricksController_upsertVariant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
        ageTier: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertVariantDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TricksController_preview: {
    parameters: {
      query: {
        ageTier: 'FORMATIVE' | 'MIDRANGE' | 'MATURE';
      };
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreviewDto'];
        };
      };
      /** @description Unknown Trick or missing variant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TricksController_versions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickVersionDto'][];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorldTricksController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        worldId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTrickDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown World. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorldTricksController_reorder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        worldId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReorderResponseDto'];
        };
      };
      /** @description Unknown World. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorldCurriculumsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        worldId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurriculumSummaryDto'][];
        };
      };
      /** @description Unknown World. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorldCurriculumsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        worldId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCurriculumDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurriculumSummaryDto'];
        };
      };
      /** @description Unknown World. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CurriculumsController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculumId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurriculumDetailDto'];
        };
      };
      /** @description Unknown Curriculum. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CurriculumsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculumId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCurriculumDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurriculumDetailDto'];
        };
      };
      /** @description Unknown Curriculum. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CurriculumsController_createSequence: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculumId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSequenceDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SequenceDetailDto'];
        };
      };
      /** @description Unknown Curriculum. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CurriculumsController_reorderSequences: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        curriculumId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReorderResponseDto'];
        };
      };
      /** @description Unknown Curriculum. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SequencesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sequenceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSequenceDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SequenceDetailDto'];
        };
      };
      /** @description Unknown Sequence. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SequencesController_setTricks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sequenceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetSequenceTricksDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SequenceDetailDto'];
        };
      };
      /** @description Unknown Sequence. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FactTypesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactTypeDto'][];
        };
      };
    };
  };
  FamiliesController_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FamilySummaryDto'][];
        };
      };
    };
  };
  FamiliesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFamilyDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FamilyDetailDto'];
        };
      };
      /** @description Unknown bound/trigger World. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FamiliesController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FamilyDetailDto'];
        };
      };
      /** @description Unknown Family. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FamiliesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFamilyDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FamilyDetailDto'];
        };
      };
      /** @description Unknown Family. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FamiliesController_createFact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFactDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Family. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FamiliesController_reorderFacts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        familyId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderFactsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderedIdsResponseDto'];
        };
      };
      /** @description Unknown Family. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FactsController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FactsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFactDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FactsController_versions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactVersionDto'][];
        };
      };
      /** @description Unknown Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InsertionsController_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sequenceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InsertionDto'][];
        };
      };
      /** @description Unknown Sequence. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  InsertionsController_replace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sequenceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetInsertionsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InsertionDto'][];
        };
      };
      /** @description Unknown Sequence or Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_setVetting: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetTrickVettingDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_setReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetReviewDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_publish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trick is not ready to publish. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_unpublish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_listComments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentDto'][];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCommentDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentDto'];
        };
      };
      /** @description Unknown Trick. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustTricksController_restoreVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trickId: string;
        versionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown Trick or version. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustVariantsController_setReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        variantId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetReviewDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TrickDetailDto'];
        };
      };
      /** @description Unknown variant. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustCommentsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCommentDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommentDto'];
        };
      };
      /** @description Unknown comment. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustFactsController_setVetting: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetFactVettingDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustFactsController_setReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetReviewDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustFactsController_publish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Fact. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Fact is not ready to publish. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TrustFactsController_restoreVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        factId: string;
        versionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FactDetailDto'];
        };
      };
      /** @description Unknown Fact or version. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OpsController_completion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompletionReportDto'];
        };
      };
      /** @description Admin access required. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OpsController_activity: {
    parameters: {
      query?: {
        /** @description Page size (bounded). */
        limit?: number;
        /** @description Rows to skip. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivityPageDto'];
        };
      };
      /** @description Admin access required. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
  HealthController_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Database reachable. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      /** @description Database unreachable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
}
